name: Purpur-Test-Plugin
version: ${version}
main: org.purpurmc.testplugin.TestPlugin
description: Purpur Test Plugin
author: PurpurMC
api-version: ${apiversion}
load: STARTUP
bootstrapper: org.purpurmc.testplugin.TestPluginBootstrap
loader: org.purpurmc.testplugin.TestPluginLoader
defaultPerm: FALSE
permissions:
dependencies:
