name: KissenPaper-Test-Plugin
version: ${version}
main: net.kissenpvp.testplugin.TestPlugin
description: KissenPaper Test Plugin
author: KissenPvP
api-version: ${apiversion}
load: STARTUP
bootstrapper: net.kissenpvp.testplugin.TestPluginBootstrap
loader: net.kissenpvp.testplugin.TestPluginLoader
defaultPerm: FALSE
permissions:
dependencies:
